package com.paymybuddy.webbapp.controller;

import com.paymybuddy.webbapp.entity.User;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.List;

public interface UserController {

    /**
     * Method for POST /user
     * this method create a new account in database for the given user.
     *
     * @param theUser the new user with: firstName, lastName, email (unique) mandatory.
     *             id is generated by Database.
     */
    public User createUser(@RequestBody User theUser);

    public String deleteUser(int thId);

    public User updateUser(User user);

    public List<User> findAll();

    public User detUserById(int theId);





}
