package com.paymybuddy.webbapp.controller;

import com.paymybuddy.webbapp.entity.User;
import com.paymybuddy.webbapp.model.CrmUser;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;

import java.util.List;

public interface UserController {

    /**
     * Method for POST /user
     * this method create a new account in database for the given user.
     *
     * @param theUser the new user with: firstName, lastName, email (unique) mandatory.
     *             id is generated by Database.
     */
    User createUser( CrmUser user, BindingResult bindingResult, Model model);

    public String deleteUser(int thId);

    public User updateUser(User user);

    public List<User> findAll();

    public User detUserById(int theId);





}
